-- MySQL Script generated by MySQL Workbench
-- Wed Sep 14 11:02:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ville` (
  `id_Ville` INT NOT NULL,
  `nom_ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Ville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exploitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exploitation` (
  `id_Exploitation` INT NOT NULL AUTO_INCREMENT,
  `nom_exploitation` VARCHAR(45) NOT NULL,
  `SAU` INT NOT NULL,
  `Ville_id_Ville` INT NOT NULL,
  PRIMARY KEY (`id_Exploitation`),
  INDEX `fk_Exploitation_Ville1_idx` (`Ville_id_Ville` ASC) VISIBLE,
  CONSTRAINT `fk_Exploitation_Ville1`
    FOREIGN KEY (`Ville_id_Ville`)
    REFERENCES `mydb`.`Ville` (`id_Ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agence` (
  `id_Agence` INT NOT NULL AUTO_INCREMENT,
  `nom_agence` VARCHAR(45) NOT NULL,
  `Ville_id_Ville` INT NOT NULL,
  PRIMARY KEY (`id_Agence`),
  INDEX `fk_Agence_Ville1_idx` (`Ville_id_Ville` ASC) VISIBLE,
  CONSTRAINT `fk_Agence_Ville1`
    FOREIGN KEY (`Ville_id_Ville`)
    REFERENCES `mydb`.`Ville` (`id_Ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comptable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comptable` (
  `id_Comptable` INT NOT NULL AUTO_INCREMENT,
  `nom_comptable` VARCHAR(20) NOT NULL,
  `prenom_comptable` VARCHAR(20) NOT NULL,
  `numtel_comptable` VARCHAR(10) NOT NULL,
  `date_naiss_comptable` DATE NOT NULL,
  `Agence_id_Agence` INT NOT NULL,
  `Exploitation_id_Exploitation` INT NOT NULL,
  PRIMARY KEY (`id_Comptable`),
  INDEX `fk_Comptable_Agence1_idx` (`Agence_id_Agence` ASC) VISIBLE,
  INDEX `fk_Comptable_Exploitation1_idx` (`Exploitation_id_Exploitation` ASC) VISIBLE,
  CONSTRAINT `fk_Comptable_Agence1`
    FOREIGN KEY (`Agence_id_Agence`)
    REFERENCES `mydb`.`Agence` (`id_Agence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comptable_Exploitation1`
    FOREIGN KEY (`Exploitation_id_Exploitation`)
    REFERENCES `mydb`.`Exploitation` (`id_Exploitation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
